"""Unit tests for the Event ORM model.

These tests do not require a database connection.  They verify column types,
defaults, constraints, and that the model is correctly configured for
SQLAlchemy 2.x typed Mapped syntax.
"""

import uuid
from datetime import datetime, timezone

import pytest
from sqlalchemy import inspect, types

from app.models.events import Event
from app.models.enums import SourceType


def test_event_tablename() -> None:
    assert Event.__tablename__ == "events"


def test_event_primary_key_column() -> None:
    mapper = inspect(Event)
    pk_cols = [col.key for col in mapper.primary_key]
    assert pk_cols == ["id"]


def test_event_columns_present() -> None:
    mapper = inspect(Event)
    col_names = {col.key for col in mapper.columns}
    expected = {
        "id",
        "source_type",
        "source_external_id",
        "content",
        "source_metadata",
        "created_at",
        "ingested_at",
        "content_hash",
    }
    assert expected <= col_names


def test_created_at_is_timezone_aware() -> None:
    mapper = inspect(Event)
    col = mapper.columns["created_at"]
    assert isinstance(col.type, types.DateTime)
    assert col.type.timezone is True


def test_ingested_at_is_timezone_aware() -> None:
    mapper = inspect(Event)
    col = mapper.columns["ingested_at"]
    assert isinstance(col.type, types.DateTime)
    assert col.type.timezone is True


def test_unique_constraint_on_source() -> None:
    table = Event.__table__
    uq_names = [c.name for c in table.constraints if hasattr(c, "columns")]
    assert "uq_events_source" in uq_names


def test_content_hash_max_length() -> None:
    mapper = inspect(Event)
    col = mapper.columns["content_hash"]
    # SHA-256 hex is 64 chars; confirm the column length cap.
    assert col.type.length == 64  # type: ignore[union-attr]


def test_event_instantiation() -> None:
    """The Event dataclass constructor works with required fields.

    id and ingested_at are init=False — auto-generated by default_factory.
    """
    now = datetime.now(tz=timezone.utc)
    event = Event(
        source_type=SourceType.doc,
        source_external_id="doc/001",
        content="Hello world",
        created_at=now,
        content_hash="a" * 64,
    )
    assert event.source_type == SourceType.doc
    assert isinstance(event.id, uuid.UUID)
    assert event.source_metadata == {}
